### ISSUE TITLE
Download file locally 

### ISSUE THREAD

**Issue by rzakfirst** [Fut1le/Firebase-Music-Streaming#1]
Hello, I admire your work, it helped me a lot to realize my project. Actually, I'm asking if it's possible to download an audio file and play it without internet connection from the app. Thank you!

**Comment by Fut1le** [comment]
Hello, thanks for the feedback! Yes, it's possible. 
You can download your track from the URL link and listen to it from the local storage. However, you won't be able to play them through JcPlayer, since it doesn't know how to work with local data.
